### ISSUE TITLE
Any links about geospatial data?

### ISSUE THREAD

**Issue by myratt** [aikho/awesome-feature-engineering#1]
Nice to have links about feature engineering for geospatial data in this list

**Comment by aikho** [comment]
Yes, I will plan to add links related to geospatial data.
But if you have some ideas about it then feel free to submit a pull request :)

**Comment by aikho** [comment]
Hi.

I have added links on awesome notebooks about feature engineering for geospatial data.
I will close this issue by now. If you will have another ideas and links worth to add then please send a PR or open another issue.
